name: Python Backup Creation

on:
  push:
    branches:
      - main  # Or any other branch you prefer to trigger the action
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # This will run the action on an Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.2 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-mock  # Optional, if you want to run tests

    - name: Run tests
      run: |
        pytest  # Run your tests using pytest
      continue-on-error: true  # Don't stop the workflow even if tests fail

    - name: Run backup creation
      run: |
        python zipped_archive.py  # Run your script to create the backup

    - name: Send email notification
      if: always()  # This ensures the email is sent regardless of test pass or fail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com  # Thef Gmail SMTP server address
        server_port: 587  # The Gmail SMTP port
        secure: true  # Use SSL for Gmail
        username: ${{ secrets.GMAIL_USERNAME }}  # GitHub Secret for your Gmail username
        password: ijvlstshbfyagzis  # GitHub Secret for your Gmail App password
        subject: "GitHub Actions Test Results"
        to: teykz974@gmail.com  # Recipient email
        from: oliviervidot974@gmail.com  # Sender's email (should match the username)
        body: |
          The tests for the project have completed. Please check the details of the test run.
          Test results: ${{ steps.tests.outputs.result }}  # This will provide the result of the tests

