name: Python Backup Creation

on:
  push:
    branches:
      - main  # Or any other branch you prefer to trigger the action
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # This will run the action on an Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.2 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-mock  # Optional, if you want to run tests

    - name: Run tests
      run: |
        pytest  # Run your tests using pytest
      continue-on-error: true  # Don't stop the workflow even if tests fail

    - name: Run backup creation
      run: |
        python zipped_archive.py  # Run your script to create the backup

    - name: Send email notification if tests fail
      if: always() 
      uses: dawidd6/action-send-mail@v3
      with:
        smtp-server: smtp.gmail.com
        smtp-port: 587
        from-email: ${{ secrets.GMAIL_USERNAME }}  # GitHub Secrets for your Gmail username
        to-email: teykz974@gmail.com  # Send the email to this address
        subject: "GitHub Actions Test Results"
        body: |
          The tests for the project have failed. Please check the details of the test run.
          Test results: ${{ steps.tests.outputs.result }}  # This will provide the result of the tests
        smtp-password: ${{ secrets.GMAIL_PASSWORD }}  # GitHub Secrets for your Gmail password or App Password